# Use the official Python image as the parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r App/requirements.txt

# Expose port 5000 for the Flask app
EXPOSE 5002

# Set environment variables
ENV KAFKA_BROKER_URL broker:29092
ENV TOPIC_NAME weather-london
ENV CASSANDRA_HOST cassandra
ENV CASSANDRA_KEYSPACE weatherdb

# Run the command to start the Flask app
CMD ["python3.8", "App/app.py"]

